---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-relay-env
data:
  smtp-relay-host: "[<YOUR-SMTP-SERVER>]:<YOUR-SMTP-SERVER-PORT>"
  smtp-relay-username: "<YOU-SMTP-AUTH-USER>"

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smtp-relay
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smtp-relay
    spec:
      containers:
        - name: smtp-relay
          image: mawich/smtp-relay
          env:
            - name: SMTP_RELAY_HOST
              valueFrom:
                configMapKeyRef:
                  name: smtp-relay-env
                  key: smtp-relay-host
            - name: SMTP_RELAY_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: smtp-relay-env
                  key: smtp-relay-username
            - name: SMTP_RELAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-relay-env
                  key: smtp-relay-password
          ports:
            - containerPort: 25

---
apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
spec:
  ports:
  - port: 25
    targetPort: 25
    protocol: TCP
  selector:
    app: smtp-relay
